---
- hosts: all
  gather_facts: False

  pre_tasks:
  - name: Install Python 2.7 for Ansible
    raw: test -e /usr/bin/python || test -e /usr/bin/python2 || test -e /usr/bin/python2.7 || test -e /usr/local/bin/python2.7 || (test -e /usr/bin/apt && apt -qqy update && apt install -qqy python) || (test -e /usr/bin/dnf && dnf install -qqy python2) || (test -e /usr/sbin/pkg && pkg install -qqy python2)
    register: output
    changed_when:
      - output.stdout != ""
      - output.stdout != "\r\n"
  
  roles:
  - jenkins